
###Register Account
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "user",
  "password": "pass",
  "email": "bob@mail.com",
  "isAdmin": "true"
}

###Login Account
POST http://localhost:3000/login
Content-Type: application/json

{
"email": "bob@mail.com",
"password": "pass"
}